version: '3.7'
services:
  
  collector:
    image: jaegertracing/jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://dll-els:9200
      # - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    external_links:
      - dll-els:dll-els
    networks:
      - els-net

  agent:
    image: jaegertracing/jaeger-agent
    environment:
      - COLLECTOR_HOST_PORT=collector:14267
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    depends_on:
      - collector
    networks:
      - els-net

  query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://dll-els:9200
      # - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - 16686:16686
    external_links:
      - dll-els:dll-els
    networks:
      - els-net
  # hotrod:
  #   image: jaegertracing/example-hotrod:1.6
  #   command: all --jaeger-agent.host-port=agent:6831
  #   ports:
  #      - 18080:8080
  #   depends_on:
  #      - agent
  #   networks:
  #      - els-net
networks:
  els-net:
    external: true 